### ISSUE TITLE
Error with code

### ISSUE THREAD

**Issue by king2022new** [Davi0k/Chess-Bot#1]
/home/runner/Chess-Bot/bot.py:357: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
  bot.add_cog(Main(bot))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/home/runner/Chess-Bot/bot.py:359: RuntimeWarning: coroutine 'BotBase.add_cog' was never awaited
  bot.add_cog(Chess(bot))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2023-06-20 01:47:03 INFO     discord.client logging in using static token
2023-06-20 01:47:04 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: d32f406d285e2bf66e81b8ace2a7ba20).
The BOT is currently online, connect to a Discord Server which contains it to start playing!
The name of the BOT is: Awain Chess Bot
The ID of the BOT is: 1120526788762796052
20-06-2023 01:47

**Comment by Davi0k** [comment]
Hello, thank you for reporting this issue.

My bad! I was kind of a noob when I wrote this application.
I forgot to add the versions in requirements.txt, so you are installing all the latest releases.
Please sync your workspace with the latest changes and try installing the dependencies again:
```
python3 -m pip install -r requirements.txt
```

It should work without any problem now!
